version: '2.2'

services:
  firehouse:
    build: ./docker-firehouse
    container_name: firehouse
    image: firehouse/firehouse
    volumes:
      - ./volumes/firehouse_private:/firehouse/private:rw
      - ./volumes/firehouse_uploads:/firehouse/uploads:rw
      - ./volumes/logs/firehouse:/logs:rw
      - ./docker-firehouse/config/app_config.yml:/firehouse/config/app_config.yml:ro
      - ./docker-firehouse/config/database.yml:/firehouse/config/database.yml:ro
      - ./docker-firehouse/config/unicorn.rb:/firehouse/config/unicorn.rb:ro
      - ./docker-firehouse/config/secrets.yml:/firehouse/config/secrets.yml:ro
      - ./docker-firehouse/custom/production.rb:/firehouse/config/environments/production.rb:ro
      - /llamadas:/firehouse/llamadas:ro
    environment:
      RAILS_ENV: production 
      SERVER_HOST: firehouse.bvgc.org
      REDIS_HOST: server.bvgc.org
      SOCKETIO_HOST: firehouse.bvgc.org
      SOCKETIO_PORT: '80'
      DB_TEST_HOST: db1.bvgc.org
      DB_TEST_NAME: firehouse_testing
      DB_TEST_USR: firehouse
      DB_TEST_PWD: 'F1r3h0us3!'
      DB_PROD_HOST: db1.bvgc.org
      DB_PROD_NAME: firehouse_production
      DB_PROD_USR: firehouse
      DB_PROD_PWD: 'F1r3h0us3!'
      CALL_CENTER_ENDPOINT: 'http://net.bvgc.org/llamadas'
    ports:
      - "8080:8080"
    restart: always

  # Implementado
  redis:
    image: redis:3
    command: redis-server /data/redis.conf
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/logs/redis:/data:rw
      - ./redis/redis.conf:/data/redis.conf
    restart: always

  # Implementado
  firealerter:
    build: ./docker-firealerter
    container_name: firealerter
    image: firehouse/firealerter:ruby2.2.10
    environment:
      REDIS_HOST: server.bvgc.org
      SERVER_HOST: firehouse.bvgc.org
      logs_path: /logs
    ports:
      - "9800:9800"
    volumes:
      - ./volumes/logs/firealerter:/logs:rw
    restart: always

  # Implementado
  broadcast:
    build: ./docker-broadcast
    container_name: broadcast
    image: firehouse/broadcast:ruby-2.2.10
    environment:
      REDIS_HOST: server.bvgc.org
      BROADCAST_IP: 10.0.10.255
      GEM_HOME: "/home/vlc/.gem"
      PATH: "$GEM_HOME/ruby/2.2.0/bin:$PATH"
      firehouse_path: /firehouse
      logs_path: /logs
    privileged: true
    pid: "host"
    network_mode: "host"
    volumes:
      - ./volumes/logs/broadcast:/logs:rw
      - ./volumes/firehouse_audio:/firehouse_audio:rw
      - ./volumes/firehouse_uploads:/firehouse/uploads:rw
    restart: always

  # Implementado
  socketio:
    build: ./docker-socketio
    container_name: socketio
    image: firehouse/socketio
    environment:
      REDIS_HOST: server.bvgc.org
    volumes:
      - ./volumes/logs:/logs:rw
    ports:
      - "8085:8085"
    restart: always

  # Implementado
  logio:
    build: ./logio
    container_name: logio
    image: firehouse/logio
    environment:
      DEBIAN_FRONTEND: noninteractive
      HOME: /home/logio
      USER: logio
    volumes:
      - ./volumes/logs:/logs:ro
    ports:
      - 8086:28778
    restart: always
