firehouse:
  build: ./firehouse
  volumes:
    - shared/:/shared:rw
    - volumes/logs:/logs:rw
    - /tmp/:/tmp:rw
  links:
    - postgres
    - redis

postgres:
  build: ./postgres
  ports:
    - "5432"
  volumes:
    - shared/:/shared:rw
    - volumes/logs:/logs:rw
    - volumes/postgres-data/:/var/lib/postgresql:rw

redis:
  build: ./redis
  ports:
    - 6379
  volumes:
    - shared/:/shared:rw
    - volumes/logs/:/logs:rw
    - volumes/redis-data/:/data:rw

nginx:
  build: ./nginx
  volumes:
    - shared/:/shared:rw
    - volumes/logs:/logs:rw
    - /tmp/:/tmp:rw
  ports:
    - 80:80

firealerter:
  build: ./firealerter
  volumes:
    - shared/:/shared:rw
    - volumes/logs:/logs:rw
  ports:
    - 9800:9800
