firehouse:
  build: ./firehouse
  privileged: true
  volumes:
    - ./shared:/shared:rw
    - ./volumes/logs:/logs:rw
    - ./volumes/logs:/firehouse/log:rw
    - /tmp:/tmp:rw
    - ./firehouse:/firehouse:rw
    - ./bundle:/bundle:rw
  links:
    - nginx
    - postgres
    - redis
    - socketio
  environment:
    SERVER_HOST: 10.0.10.200

postgres:
  build: ./postgres
  ports:
    - 5432:5432
  volumes:
    - ./volumes/logs:/logs:rw
    - ./volumes/postgres/data:/var/lib/postgresql/data:rw
  environment:
    SERVER_HOST: 10.0.10.200

redis:
  build: ./redis
  privileged: true
  ports:
    - 6379:6379
  volumes:
    - ./volumes/logs:/logs:rw
    - ./volumes/redis:/var/lib/redis:rw
  environment:
    SERVER_HOST: 10.0.10.200

nginx:
  build: ./nginx
  volumes:
    - shared/:/shared:rw
    - firehouse/:/firehouse:ro
    - volumes/logs:/logs:rw
    - /tmp/:/tmp:rw
  ports:
    - 80:80

firealerter:
  build: ./firealerter
  volumes:
    - volumes/logs:/logs:rw
    - bundle/:/bundle:rw
  links:
    - redis
  ports:
    - 9800:9800
  environment:
    SERVER_HOST: 10.0.10.200

broadcast:
  build: ./broadcast
  environment:
    firehouse_path: /firehouse
    logs_path: /logs
    SERVER_HOST: 10.0.10.200
    BROADCAST_IP: 10.0.10.255
  privileged: true
  net: host
  volumes_from:
    - firehouse

socketio:
  build: ./socketio
  volumes:
    - volumes/logs:/logs:rw
  links:
    - redis
  ports:
    - 8085:8085
  environment:
    SERVER_HOST: 10.0.10.200

logio:
  build: ./logio
  volumes:
    - volumes/logs:/logs:rw
  ports:
    - 8086:28778

cacher:
  build: ./apt_cacher
  volumes:
    - volumes/cache:/var/cache/apt-cacher-ng:rw
  ports:
    - 3142:3142

gps:
  build: ./gps_tracker
  ports:
    - 34567:34567
  links:
    - postgres
  volumes:
    - ./volumes/logs/gps:/gps_tracker/log:rw
  environment:
    project_public_dir: /gps_tracker

squid:
	image: fgrehm/squid3-ssl:v20140809
  volumes:
    - volumes/squid/cache:/var/spool/squid3:rw
    - volumes/logs/squid:/var/log/squid3:rw
    - proxy.docker.dev.crt:/usr/share/ca-certificates/proxy.docker.dev.crt
  ports:
    - 3128:3128
