version: '2.2'

services:
  firehouse:
    container_name: firehouse
    image: shelvak/firehouse:latest
    volumes:
      - ./volumes/firehouse_private:/firehouse/private:rw
      - ./volumes/firehouse_uploads:/firehouse/uploads:rw
      - ./volumes/logs/firehouse:/logs:rw
      - ./firehouse/secrets.yml:/firehouse/config/secrets.yml:ro
      - /llamadas:/firehouse/llamadas:ro
    env_file:
      - ./firehouse/.env
    ports:
      - "8080:8080"
    restart: always

  redis:
    image: redis:3
    command: redis-server /data/redis.conf
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/logs/redis/:/logs/:rw
      - ./redis/:/data/:rw
    restart: always

  firealerter:
    container_name: firealerter
    image: shelvak/firealerter:latest
    env_file:
      - ./firealerter/.env
    ports:
      - "9800:9800"
    volumes:
      - ./volumes/logs/firealerter:/logs:rw
    restart: always

  broadcast:
    container_name: broadcast
    image: shelvak/firehouse_audio:latest
    env_file:
      - ./broadcast/.env
    privileged: true
    pid: "host"
    network_mode: "host"
    volumes:
      - ./volumes/logs/broadcast:/logs:rw
      - ./volumes/firehouse_uploads:/firehouse/uploads:rw
    restart: always

  socketio:
    container_name: socketio
    image: shelvak/firehouse_socketio:latest
    env_file:
      - ./socketio/.env
    volumes:
      - ./volumes/logs:/logs:rw
    ports:
      - "8085:8085"
    restart: always

  logio:
    container_name: logio
    image: shelvak/docker-log.io:latest
    volumes:
      - ./logio/harvester.conf:/home/logio/.log.io/harvester.conf:ro
      - ./volumes/logs:/logs:ro
    ports:
      - 8086:28778
    restart: always
