firehouse:
  build: ./firehouse
  privileged: true
  volumes:
    - shared/:/shared:rw
    - volumes/logs:/logs:rw
    - volumes/logs:/firehouse/log:rw
    - /tmp/:/tmp:rw
    - firehouse/:/firehouse:rw
  links:
    - nginx
    - postgres
    - redis
    - socketio
  environment:
    SERVER_HOST: 192.168.1.200
    http_proxy: http://dockerhost:3142/

postgres:
  build: ./postgres
  ports:
    - 5432:5432
  volumes:
    - shared/:/shared:rw
    - volumes/logs:/logs:rw
    - volumes/postgres-data/:/var/lib/postgresql:rw
  environment:
    SERVER_HOST: 192.168.1.200
    http_proxy: http://dockerhost:3142/

redis:
  build: ./redis
  ports:
    - 6379:6379
  volumes:
    - shared/:/shared:rw
    - volumes/logs/:/logs:rw
    - volumes/redis-data/:/data:rw
  environment:
    SERVER_HOST: 192.168.1.200
    http_proxy: http://dockerhost:3142/

nginx:
  build: ./nginx
  volumes:
    - shared/:/shared:rw
    - firehouse/:/firehouse:ro
    - volumes/logs:/logs:rw
    - /tmp/:/tmp:rw
  ports:
    - 80:80
  environment:
    http_proxy: http://dockerhost:3142/

firealerter:
  build: ./firealerter
  volumes:
    - shared/:/shared:rw
    - volumes/logs:/logs:rw
  links:
    - redis
  ports:
    - 9800:9800
  environment:
    SERVER_HOST: 192.168.1.200
    http_proxy: http://dockerhost:3142/

broadcast:
  build: ./broadcast
  environment:
    firehouse_path: /firehouse
    logs_path: /logs
    SERVER_HOST: 192.168.1.200
    http_proxy: http://dockerhost:3142/
  privileged: true
  net: host
  volumes_from:
    - firehouse

socketio:
  build: ./socketio
  volumes:
    - shared/:/shared:rw
    - volumes/logs:/logs:rw
  links:
    - redis
  ports:
    - 8085:8085
  environment:
    SERVER_HOST: 192.168.1.200
    http_proxy: http://dockerhost:3142/

logio:
  build: ./logio
  volumes:
    - shared/:/shared:rw
    - volumes/logs:/logs:rw
  ports:
    - 8086:28778
  environment:
    http_proxy: http://dockerhost:3142/

apt_cacher:
  build: ./apt_cacher
  volumes:
    - volumes/cache:/var/cache/apt-cacher-ng:rw
  ports:
    - 3142
