firehouse:
  build: ./firehouse
  # privileged: true
  volumes:
    - ./shared:/shared:rw
    - ./volumes/logs:/logs:rw
    - ./volumes/logs/firehouse:/firehouse/log:rw
    - /tmp:/tmp:rw
    - ./firehouse:/firehouse:rw
    - ./volumes/bundle:/bundle:rw
  links:
    - nginx
    - postgres
    - redis
    - socketio
  environment:
    SERVER_HOST: server.bvgc.org

postgres:
  build: ./postgres
  ports:
    - 5432:5432
  volumes:
    - shared/:/shared:rw
    - ./volumes/logs:/logs:rw
    - ./volumes/postgres/data:/var/lib/postgresql/data:rw
    - ./postgres/postgresql.conf:/etc/postgres/9.3/main/postgresql.conf
    - ./postgres/pg_hba.conf:/etc/postgres/9.3/main/pg_hba.conf
  environment:
    DOCKER_HOST_IP: 172.17.0.1
    SERVER_HOST: server.bvgc.org

redis:
  build: ./redis
  # privileged: true
  ports:
    - 6379:6379
  volumes:
    - ./volumes/logs:/logs:rw
    - ./volumes/redis:/var/lib/redis:rw
  environment:
    SERVER_HOST: server.bvgc.org

nginx:
  build: ./nginx
  volumes:
    - ./shared/:/shared:rw
    - ./firehouse/:/firehouse:ro
    - ./gps_tracker/:/gps_tracker:ro
    - ./volumes/logs:/logs:rw
    - /tmp:/tmp:rw
  ports:
    - 80:80

firealerter:
  build: ./firealerter
  volumes:
    - ./volumes/logs:/logs:rw
    - ./volumes/bundle:/bundle:rw
  links:
    - redis
  ports:
    - 9800:9800
  environment:
    SERVER_HOST: server.bvgc.org

broadcast:
  build: ./broadcast
  environment:
    firehouse_path: /firehouse
    logs_path: /logs
    SERVER_HOST: server.bvgc.org
    BROADCAST_IP: 10.0.10.255
  #links:
  #  - redis
  privileged: true
  net: host
  user: vlc
  volumes_from:
    - firehouse

socketio:
  build: ./socketio
  volumes:
    - ./volumes/logs:/logs:rw
  links:
    - redis
  ports:
    - 8085:8085
  environment:
    SERVER_HOST: server.bvgc.org

logio:
  build: ./logio
  volumes:
    - ./volumes/logs:/logs:ro
  ports:
    - 8086:28778

gpsmilonga:
  build: ./gps_tracker
  volumes:
    - ./shared:/shared:rw
    - ./volumes/logs/gps:/gps_tracker/log:rw
    - ./volumes/logs:/logs:rw
    - ./gps_tracker:/gps_tracker:rw
    #- ./volumes/bundle:/bundle:rw
  links:
    - nginx
    - postgres
  ports:
    - 3003:34567
  environment:
    project_public_dir: /gps_tracker

squid:
  build: squid/
  volumes:
    - ./shared/:/shared:rw
    - ./volumes/squid/cache:/var/cache/squid3:rw
    - ./volumes/logs/squid:/var/log/squid3:rw
  ports:
    - 3128:3128

osmtiles_on_demand:
  image: klokantech/tileserver-gl:v2.1.0
  volumes:
    - ./volumes/osm-tiles:/data:rw
  ports:
    - 8881:80


osmtiles_postgres:
  image: smartroadsense/osm-tiles
  # user: root
  environment:
    OSM_DB_USER: osm
    OSM_DB_PASS: osm
    OSM_DB_HOST: postgres
    OSM_DB_PORT: 5432
    OSM_DB_NAME: osm
  links:
    - postgres
  volumes:
    - ./volumes/osm-tiles-postgres/data:/data:rw
    - ./volumes/osm-tiles-postgres/db:/var/lib/postgresql:rw
    - ./volumes/osm-tiles-postgres/mod_tile:/var/lib/mod_tile:rw
    - ./osm-configs/OSMBright.xml:/opt/osm-bright-master/OSMBright/OSMBright.xml
    - ./osm-configs/osm_tiles-docker-entrypoint.sh:/docker-entrypoint.sh:rw
  ports:
    - 8882:8000

osrm:
  image: osrm/osrm-backend:v5.9.2
  volumes:
    - ./volumes/osrm-backed:/data:rw
  ports:
    - 5000:5000

