firehouse:
  build: ./firehouse
  privileged: true
  volumes:
    - /dev/snd:/dev/snd:rw
    - shared/:/shared:rw
    - volumes/logs:/logs:rw
    - volumes/logs:/firehouse/log:rw
    - /tmp/:/tmp:rw
    - firehouse/:/firehouse:rw
  links:
    - nginx
    - postgres
    - redis
    - socketio
  environment:
    SERVER_HOST: 192.168.1.200

postgres:
  build: ./postgres
  ports:
    - 5432:5432
  volumes:
    - shared/:/shared:rw
    - volumes/logs:/logs:rw
    - volumes/postgres-data/:/var/lib/postgresql:rw
  environment:
    SERVER_HOST: 192.168.1.200

redis:
  build: ./redis
  ports:
    - 6379:6379
  volumes:
    - shared/:/shared:rw
    - volumes/logs/:/logs:rw
    - volumes/redis-data/:/data:rw
  environment:
    SERVER_HOST: 192.168.1.200

nginx:
  build: ./nginx
  volumes:
    - shared/:/shared:rw
    - firehouse/:/firehouse:ro
    - volumes/logs:/logs:rw
    - /tmp/:/tmp:rw
  ports:
    - 80:80

firealerter:
  build: ./firealerter
  volumes:
    - shared/:/shared:rw
    - volumes/logs:/logs:rw
  links:
    - redis
  ports:
    - 9800:9800
  environment:
    SERVER_HOST: 192.168.1.200

broadcast:
  build: ./broadcast
  environment:
    firehouse_path: /firehouse
    logs_path: /logs
    SERVER_HOST: 192.168.1.200
  privileged: true
  net: host
  volumes_from:
    - firehouse

socketio:
  build: ./socketio
  volumes:
    - shared/:/shared:rw
    - volumes/logs:/logs:rw
  links:
    - redis
  ports:
    - 8085:8085
  environment:
    SERVER_HOST: 192.168.1.200

logio:
  build: ./logio
  volumes:
    - shared/:/shared:rw
    - volumes/logs:/logs:rw
  ports:
    - 28778:28778
