firehouse:
  build: ./firehouse
  privileged: true
  volumes:
    - ./shared:/shared:rw
    - ./volumes/logs:/logs:rw
    - ./volumes/logs/firehouse:/firehouse/log:rw
    - /tmp:/tmp:rw
    - ./firehouse:/firehouse:rw
    - ./volumes/bundle:/bundle:rw
  links:
    - nginx
    - postgres
    - redis
    - socketio
  environment:
    SERVER_HOST: 10.0.10.200

postgres:
  build: ./postgres
  ports:
    - 5432:5432
  volumes:
    - shared/:/shared:rw
    - ./volumes/logs:/logs:rw
    - ./volumes/postgres/data:/var/lib/postgresql/data:rw
  environment:
    DOCKER_HOST_IP: 172.17.0.1
    SERVER_HOST: 10.0.10.200

redis:
  build: ./redis
  privileged: true
  ports:
    - 6379:6379
  volumes:
    - ./volumes/logs:/logs:rw
    - ./volumes/redis:/var/lib/redis:rw
  environment:
    SERVER_HOST: 10.0.10.200

nginx:
  build: ./nginx
  volumes:
    - ./shared/:/shared:rw
    - ./firehouse/:/firehouse:ro
    - ./gps_tracker/:/gps_tracker:ro
    - ./volumes/logs:/logs:rw
    - /tmp/:/tmp:rw
  ports:
    - 80:80
    - 85:85

firealerter:
  build: ./firealerter
  volumes:
    - ./volumes/logs:/logs:rw
    - ./volumes/bundle:/bundle:rw
  links:
    - redis
  ports:
    - 9800:9800
  environment:
    SERVER_HOST: 10.0.10.200

broadcast:
  build: ./broadcast
  environment:
    firehouse_path: /firehouse
    logs_path: /logs
    SERVER_HOST: 10.0.10.200
    BROADCAST_IP: 10.0.10.255
  privileged: true
  net: host
  volumes_from:
    - firehouse

socketio:
  build: ./socketio
  volumes:
    - ./volumes/logs:/logs:rw
  links:
    - redis
  ports:
    - 8085:8085
  environment:
    SERVER_HOST: 10.0.10.200

logio:
  build: ./logio
  volumes:
    - ./volumes/logs:/logs:ro
  ports:
    - 8086:28778

gpsmilonga:
  build: ./gps_tracker
  volumes:
    - ./shared:/shared:rw
    - ./volumes/logs/gps:/gps_tracker/log:rw
    - ./volumes/logs:/logs:rw
    - ./gps_tracker:/gps_tracker:rw
    #- ./volumes/bundle:/bundle:rw
  links:
    - nginx
    - postgres
  ports:
    - 3003:34567
  environment:
    project_public_dir: /gps_tracker

squid:
  build: squid/
  volumes:
    - ./shared/:/shared:rw
    - ./volumes/squid/cache:/var/cache/squid3:rw
    - ./volumes/logs/squid:/var/log/squid3:rw
  ports:
    - 3128:3128
