defaults: &defaults
  secret_key_base: ecbae5de81aae202f6b859737f2072f45202aea4f6ddb7617a6522e0f57219d5f47da407d76a3a1b72ac61e6d6a9077f0bdebd9cdefa6cca0a678dc3ac711f3c
  bugsnag_api_key: '6e83567364e1ed60bba5ae498b6f18ca'
  google_api_key: 'AIzaSyA_YXAXLKwObcDAW6drge_WxNzVKWfOQBg'
  email:
    address: 'smtp.gmail.com'
    port: 587
    domain: 'gmail.com'
    user_name: 'bvgc.alerter@gmail.com'
    password: '(UHB&YHN5rdx4rfv'
    authentication: 'plain'
    enable_starttls_auto: true


development:
  <<: *defaults
production:
  <<: *defaults
test:
  <<: *defaults
